name: malf_study
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.2
  http: ^1.1.0
  image_picker: ^1.0.1
  logger: ^1.4.0
  provider: ^6.0.5
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
